# Site settings
title: Sonimy's Zone
description: "Eat your own dog food."
author:
  username: Sonimy
  twitter: sonimy
  github: sonimy
  email: fieldsman@qq.com
baseurl: ""
url: "https://sonimy.github.com"

# Build settings
markdown: kramdown
permalink: /:categories/:year-:month/:title.html
excerpt_separator: "\n\n\n"